[package]
name = "mountaindouw/cleanit"
version = "2.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "A memory cleaning helper."
authors = ["ProphetOuw <ouwproduction@gmail.com>"]